apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80          # The port exposed by the LoadBalancer
      targetPort: 8080  # The port on the container where the application is listening
  type: LoadBalancer    # Change the service type to LoadBalancer
