apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 8080  
      nodePort: 32000  
  type: NodePort  # Type of service
